# This is a basic workflow to help you get started with Actions

name: CI Linting and Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up npm
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Linting check
      run: |
        # now check install works and check for any lint issues
        npm install
        npm run checkLint
    - name: Build Docs
      run: |
        # ensure able to build the docs
        npm run docs
    - name: Upload Documentation
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: docs
    - name: Cypress Tests
      run: |
        nohup npm start
        npm run cypress:test
    - name: Upload Video Run
      uses: actions/upload-artifact@v1
      with:
        name: cypress-videos
        path: cypress/videos

